package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.BasCities;
import com.yanghua.gongxiang.bean.BasCitiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasCitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_cities
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    long countByExample(BasCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_cities
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int deleteByExample(BasCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_cities
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int insert(BasCities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_cities
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int insertSelective(BasCities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_cities
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    List<BasCities> selectByExample(BasCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_cities
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") BasCities record, @Param("example") BasCitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_cities
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int updateByExample(@Param("record") BasCities record, @Param("example") BasCitiesExample example);
}