package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.BasCounties;
import com.yanghua.gongxiang.bean.BasCountiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasCountiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_counties
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    long countByExample(BasCountiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_counties
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    int deleteByExample(BasCountiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_counties
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    int insert(BasCounties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_counties
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    int insertSelective(BasCounties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_counties
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    List<BasCounties> selectByExample(BasCountiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_counties
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") BasCounties record, @Param("example") BasCountiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_counties
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    int updateByExample(@Param("record") BasCounties record, @Param("example") BasCountiesExample example);
}