package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.BasProvinces;
import com.yanghua.gongxiang.bean.BasProvincesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasProvincesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_provinces
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    long countByExample(BasProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_provinces
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int deleteByExample(BasProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_provinces
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int insert(BasProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_provinces
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int insertSelective(BasProvinces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_provinces
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    List<BasProvinces> selectByExample(BasProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_provinces
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") BasProvinces record, @Param("example") BasProvincesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_provinces
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    int updateByExample(@Param("record") BasProvinces record, @Param("example") BasProvincesExample example);
}