package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.BasRegions;
import com.yanghua.gongxiang.bean.BasRegionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasRegionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    long countByExample(BasRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int deleteByExample(BasRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int insert(BasRegions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int insertSelective(BasRegions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    List<BasRegions> selectByExample(BasRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    BasRegions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") BasRegions record, @Param("example") BasRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int updateByExample(@Param("record") BasRegions record, @Param("example") BasRegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int updateByPrimaryKeySelective(BasRegions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_bas_regions
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    int updateByPrimaryKey(BasRegions record);
}