package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.ContentType;
import com.yanghua.gongxiang.bean.ContentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    long countByExample(ContentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByExample(ContentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insert(ContentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insertSelective(ContentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    List<ContentType> selectByExample(ContentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    ContentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContentType record, @Param("example") ContentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExample(@Param("record") ContentType record, @Param("example") ContentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKeySelective(ContentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKey(ContentType record);
}