package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.Depts;
import com.yanghua.gongxiang.bean.DeptsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    long countByExample(DeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByExample(DeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insert(Depts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insertSelective(Depts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    List<Depts> selectByExample(DeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    Depts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Depts record, @Param("example") DeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExample(@Param("record") Depts record, @Param("example") DeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKeySelective(Depts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKey(Depts record);
}