package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.SysLogs;
import com.yanghua.gongxiang.bean.SysLogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    long countByExample(SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByExample(SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insert(SysLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insertSelective(SysLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    List<SysLogs> selectByExample(SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    SysLogs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysLogs record, @Param("example") SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExample(@Param("record") SysLogs record, @Param("example") SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKeySelective(SysLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_sys_logs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKey(SysLogs record);
}