package com.yanghua.gongxiang.dao;

import com.yanghua.gongxiang.bean.Users;
import com.yanghua.gongxiang.bean.UsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    List<Users> selectByExampleWithBLOBs(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    Users selectByPrimaryKey(Integer id);

    Users selectByName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_users
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    int updateByPrimaryKey(Users record);
    //    selectByUsername
    List<Users> selectByUsername();
    Users FindUserByUsername( @Param("username") String username);
}