package com.yanghua.gongxiang.bean;

public class BasCities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_cities.id
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_cities.cityID
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    private Integer cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_cities.cityName
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    private String cityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_cities.father
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    private Integer father;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_cities.id
     *
     * @return the value of gx_bas_cities.id
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_cities.id
     *
     * @param id the value for gx_bas_cities.id
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_cities.cityID
     *
     * @return the value of gx_bas_cities.cityID
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_cities.cityID
     *
     * @param cityid the value for gx_bas_cities.cityID
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_cities.cityName
     *
     * @return the value of gx_bas_cities.cityName
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_cities.cityName
     *
     * @param cityname the value for gx_bas_cities.cityName
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_cities.father
     *
     * @return the value of gx_bas_cities.father
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public Integer getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_cities.father
     *
     * @param father the value for gx_bas_cities.father
     *
     * @mbg.generated Fri Jan 26 16:56:30 CST 2018
     */
    public void setFather(Integer father) {
        this.father = father;
    }
}