package com.yanghua.gongxiang.bean;

public class BasCounties {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_counties.id
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_counties.areaID
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_counties.areaName
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_counties.father
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    private Integer father;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_counties.id
     *
     * @return the value of gx_bas_counties.id
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_counties.id
     *
     * @param id the value for gx_bas_counties.id
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_counties.areaID
     *
     * @return the value of gx_bas_counties.areaID
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_counties.areaID
     *
     * @param areaid the value for gx_bas_counties.areaID
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_counties.areaName
     *
     * @return the value of gx_bas_counties.areaName
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_counties.areaName
     *
     * @param areaname the value for gx_bas_counties.areaName
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_counties.father
     *
     * @return the value of gx_bas_counties.father
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public Integer getFather() {
        return father;
    }

    @Override
    public String toString() {
        return "BasCounties{" +
                "id=" + id +
                ", areaid=" + areaid +
                ", areaname='" + areaname + '\'' +
                ", father=" + father +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_counties.father
     *
     * @param father the value for gx_bas_counties.father
     *
     * @mbg.generated Fri Jan 26 16:57:58 CST 2018
     */
    public void setFather(Integer father) {
        this.father = father;
    }
}