package com.yanghua.gongxiang.bean;

public class BasRegions {
    @Override
    public String toString() {
        return "BasRegions{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", provIds='" + provIds + '\'' +
                ", orderNum=" + orderNum +
                ", status=" + status +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_regions.id
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_regions.name
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_regions.prov_ids
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    private String provIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_regions.order_num
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_bas_regions.status
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_regions.id
     *
     * @return the value of gx_bas_regions.id
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_regions.id
     *
     * @param id the value for gx_bas_regions.id
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_regions.name
     *
     * @return the value of gx_bas_regions.name
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_regions.name
     *
     * @param name the value for gx_bas_regions.name
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_regions.prov_ids
     *
     * @return the value of gx_bas_regions.prov_ids
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public String getProvIds() {
        return provIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_regions.prov_ids
     *
     * @param provIds the value for gx_bas_regions.prov_ids
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public void setProvIds(String provIds) {
        this.provIds = provIds == null ? null : provIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_regions.order_num
     *
     * @return the value of gx_bas_regions.order_num
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_regions.order_num
     *
     * @param orderNum the value for gx_bas_regions.order_num
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_bas_regions.status
     *
     * @return the value of gx_bas_regions.status
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_bas_regions.status
     *
     * @param status the value for gx_bas_regions.status
     *
     * @mbg.generated Sat Jan 27 14:24:12 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}