package com.yanghua.gongxiang.bean;

import java.util.Date;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.shortname
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.abbrcode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String abbrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.logo_file
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String logoFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.addr
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.zip
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.tel
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.fax
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.website
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.postmail
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String postmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.is_sys
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte isSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.created_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.created_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.updated_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer updatedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_company.updated_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.id
     *
     * @return the value of gx_company.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.id
     *
     * @param id the value for gx_company.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.name
     *
     * @return the value of gx_company.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.name
     *
     * @param name the value for gx_company.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.shortname
     *
     * @return the value of gx_company.shortname
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.shortname
     *
     * @param shortname the value for gx_company.shortname
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.abbrcode
     *
     * @return the value of gx_company.abbrcode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getAbbrcode() {
        return abbrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.abbrcode
     *
     * @param abbrcode the value for gx_company.abbrcode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setAbbrcode(String abbrcode) {
        this.abbrcode = abbrcode == null ? null : abbrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.logo_file
     *
     * @return the value of gx_company.logo_file
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getLogoFile() {
        return logoFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.logo_file
     *
     * @param logoFile the value for gx_company.logo_file
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setLogoFile(String logoFile) {
        this.logoFile = logoFile == null ? null : logoFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.addr
     *
     * @return the value of gx_company.addr
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.addr
     *
     * @param addr the value for gx_company.addr
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.zip
     *
     * @return the value of gx_company.zip
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.zip
     *
     * @param zip the value for gx_company.zip
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.tel
     *
     * @return the value of gx_company.tel
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.tel
     *
     * @param tel the value for gx_company.tel
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.fax
     *
     * @return the value of gx_company.fax
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.fax
     *
     * @param fax the value for gx_company.fax
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.website
     *
     * @return the value of gx_company.website
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.website
     *
     * @param website the value for gx_company.website
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.postmail
     *
     * @return the value of gx_company.postmail
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getPostmail() {
        return postmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.postmail
     *
     * @param postmail the value for gx_company.postmail
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setPostmail(String postmail) {
        this.postmail = postmail == null ? null : postmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.is_sys
     *
     * @return the value of gx_company.is_sys
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.is_sys
     *
     * @param isSys the value for gx_company.is_sys
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIsSys(Byte isSys) {
        this.isSys = isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.order_num
     *
     * @return the value of gx_company.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.order_num
     *
     * @param orderNum the value for gx_company.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.status
     *
     * @return the value of gx_company.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.status
     *
     * @param status the value for gx_company.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.created_id
     *
     * @return the value of gx_company.created_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.created_id
     *
     * @param createdId the value for gx_company.created_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setCreatedId(Integer createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.created_time
     *
     * @return the value of gx_company.created_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.created_time
     *
     * @param createdTime the value for gx_company.created_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.updated_id
     *
     * @return the value of gx_company.updated_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getUpdatedId() {
        return updatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.updated_id
     *
     * @param updatedId the value for gx_company.updated_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setUpdatedId(Integer updatedId) {
        this.updatedId = updatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_company.updated_time
     *
     * @return the value of gx_company.updated_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_company.updated_time
     *
     * @param updatedTime the value for gx_company.updated_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}