package com.yanghua.gongxiang.bean;

public class ContentType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.menu_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.parent_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.tp_name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String tpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.tp_desc
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String tpDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.tp_image
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String tpImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.tp_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Short tpMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.code_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Short codeMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.tp_path
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String tpPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.tp_show
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Short tpShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.is_top
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.top_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Short topMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.top_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer topNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String depts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.is_sign
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Boolean isSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_content_type.sign_ids
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String signIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.id
     *
     * @return the value of gx_content_type.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.id
     *
     * @param id the value for gx_content_type.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.menu_id
     *
     * @return the value of gx_content_type.menu_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.menu_id
     *
     * @param menuId the value for gx_content_type.menu_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.parent_id
     *
     * @return the value of gx_content_type.parent_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.parent_id
     *
     * @param parentId the value for gx_content_type.parent_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.tp_name
     *
     * @return the value of gx_content_type.tp_name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getTpName() {
        return tpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.tp_name
     *
     * @param tpName the value for gx_content_type.tp_name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTpName(String tpName) {
        this.tpName = tpName == null ? null : tpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.tp_desc
     *
     * @return the value of gx_content_type.tp_desc
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getTpDesc() {
        return tpDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.tp_desc
     *
     * @param tpDesc the value for gx_content_type.tp_desc
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTpDesc(String tpDesc) {
        this.tpDesc = tpDesc == null ? null : tpDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.tp_image
     *
     * @return the value of gx_content_type.tp_image
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getTpImage() {
        return tpImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.tp_image
     *
     * @param tpImage the value for gx_content_type.tp_image
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTpImage(String tpImage) {
        this.tpImage = tpImage == null ? null : tpImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.tp_mode
     *
     * @return the value of gx_content_type.tp_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Short getTpMode() {
        return tpMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.tp_mode
     *
     * @param tpMode the value for gx_content_type.tp_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTpMode(Short tpMode) {
        this.tpMode = tpMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.code_mode
     *
     * @return the value of gx_content_type.code_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Short getCodeMode() {
        return codeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.code_mode
     *
     * @param codeMode the value for gx_content_type.code_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setCodeMode(Short codeMode) {
        this.codeMode = codeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.tp_path
     *
     * @return the value of gx_content_type.tp_path
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getTpPath() {
        return tpPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.tp_path
     *
     * @param tpPath the value for gx_content_type.tp_path
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTpPath(String tpPath) {
        this.tpPath = tpPath == null ? null : tpPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.tp_show
     *
     * @return the value of gx_content_type.tp_show
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Short getTpShow() {
        return tpShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.tp_show
     *
     * @param tpShow the value for gx_content_type.tp_show
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTpShow(Short tpShow) {
        this.tpShow = tpShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.is_top
     *
     * @return the value of gx_content_type.is_top
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.is_top
     *
     * @param isTop the value for gx_content_type.is_top
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIsTop(Byte isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.top_mode
     *
     * @return the value of gx_content_type.top_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Short getTopMode() {
        return topMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.top_mode
     *
     * @param topMode the value for gx_content_type.top_mode
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTopMode(Short topMode) {
        this.topMode = topMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.top_num
     *
     * @return the value of gx_content_type.top_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getTopNum() {
        return topNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.top_num
     *
     * @param topNum the value for gx_content_type.top_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTopNum(Integer topNum) {
        this.topNum = topNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.order_num
     *
     * @return the value of gx_content_type.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.order_num
     *
     * @param orderNum the value for gx_content_type.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.status
     *
     * @return the value of gx_content_type.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.status
     *
     * @param status the value for gx_content_type.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.depts
     *
     * @return the value of gx_content_type.depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getDepts() {
        return depts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.depts
     *
     * @param depts the value for gx_content_type.depts
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setDepts(String depts) {
        this.depts = depts == null ? null : depts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.is_sign
     *
     * @return the value of gx_content_type.is_sign
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Boolean getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.is_sign
     *
     * @param isSign the value for gx_content_type.is_sign
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIsSign(Boolean isSign) {
        this.isSign = isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_content_type.sign_ids
     *
     * @return the value of gx_content_type.sign_ids
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getSignIds() {
        return signIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_content_type.sign_ids
     *
     * @param signIds the value for gx_content_type.sign_ids
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setSignIds(String signIds) {
        this.signIds = signIds == null ? null : signIds.trim();
    }
}