package com.yanghua.gongxiang.bean;

import java.util.ArrayList;
import java.util.List;

public class ContentTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public ContentTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("menu_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(Integer value) {
            addCriterion("menu_id =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(Integer value) {
            addCriterion("menu_id <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(Integer value) {
            addCriterion("menu_id >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_id >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(Integer value) {
            addCriterion("menu_id <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Integer value) {
            addCriterion("menu_id <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<Integer> values) {
            addCriterion("menu_id in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<Integer> values) {
            addCriterion("menu_id not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(Integer value1, Integer value2) {
            addCriterion("menu_id between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_id not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andTpNameIsNull() {
            addCriterion("tp_name is null");
            return (Criteria) this;
        }

        public Criteria andTpNameIsNotNull() {
            addCriterion("tp_name is not null");
            return (Criteria) this;
        }

        public Criteria andTpNameEqualTo(String value) {
            addCriterion("tp_name =", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameNotEqualTo(String value) {
            addCriterion("tp_name <>", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameGreaterThan(String value) {
            addCriterion("tp_name >", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameGreaterThanOrEqualTo(String value) {
            addCriterion("tp_name >=", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameLessThan(String value) {
            addCriterion("tp_name <", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameLessThanOrEqualTo(String value) {
            addCriterion("tp_name <=", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameLike(String value) {
            addCriterion("tp_name like", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameNotLike(String value) {
            addCriterion("tp_name not like", value, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameIn(List<String> values) {
            addCriterion("tp_name in", values, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameNotIn(List<String> values) {
            addCriterion("tp_name not in", values, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameBetween(String value1, String value2) {
            addCriterion("tp_name between", value1, value2, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpNameNotBetween(String value1, String value2) {
            addCriterion("tp_name not between", value1, value2, "tpName");
            return (Criteria) this;
        }

        public Criteria andTpDescIsNull() {
            addCriterion("tp_desc is null");
            return (Criteria) this;
        }

        public Criteria andTpDescIsNotNull() {
            addCriterion("tp_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTpDescEqualTo(String value) {
            addCriterion("tp_desc =", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescNotEqualTo(String value) {
            addCriterion("tp_desc <>", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescGreaterThan(String value) {
            addCriterion("tp_desc >", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescGreaterThanOrEqualTo(String value) {
            addCriterion("tp_desc >=", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescLessThan(String value) {
            addCriterion("tp_desc <", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescLessThanOrEqualTo(String value) {
            addCriterion("tp_desc <=", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescLike(String value) {
            addCriterion("tp_desc like", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescNotLike(String value) {
            addCriterion("tp_desc not like", value, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescIn(List<String> values) {
            addCriterion("tp_desc in", values, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescNotIn(List<String> values) {
            addCriterion("tp_desc not in", values, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescBetween(String value1, String value2) {
            addCriterion("tp_desc between", value1, value2, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpDescNotBetween(String value1, String value2) {
            addCriterion("tp_desc not between", value1, value2, "tpDesc");
            return (Criteria) this;
        }

        public Criteria andTpImageIsNull() {
            addCriterion("tp_image is null");
            return (Criteria) this;
        }

        public Criteria andTpImageIsNotNull() {
            addCriterion("tp_image is not null");
            return (Criteria) this;
        }

        public Criteria andTpImageEqualTo(String value) {
            addCriterion("tp_image =", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageNotEqualTo(String value) {
            addCriterion("tp_image <>", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageGreaterThan(String value) {
            addCriterion("tp_image >", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageGreaterThanOrEqualTo(String value) {
            addCriterion("tp_image >=", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageLessThan(String value) {
            addCriterion("tp_image <", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageLessThanOrEqualTo(String value) {
            addCriterion("tp_image <=", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageLike(String value) {
            addCriterion("tp_image like", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageNotLike(String value) {
            addCriterion("tp_image not like", value, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageIn(List<String> values) {
            addCriterion("tp_image in", values, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageNotIn(List<String> values) {
            addCriterion("tp_image not in", values, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageBetween(String value1, String value2) {
            addCriterion("tp_image between", value1, value2, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpImageNotBetween(String value1, String value2) {
            addCriterion("tp_image not between", value1, value2, "tpImage");
            return (Criteria) this;
        }

        public Criteria andTpModeIsNull() {
            addCriterion("tp_mode is null");
            return (Criteria) this;
        }

        public Criteria andTpModeIsNotNull() {
            addCriterion("tp_mode is not null");
            return (Criteria) this;
        }

        public Criteria andTpModeEqualTo(Short value) {
            addCriterion("tp_mode =", value, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeNotEqualTo(Short value) {
            addCriterion("tp_mode <>", value, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeGreaterThan(Short value) {
            addCriterion("tp_mode >", value, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeGreaterThanOrEqualTo(Short value) {
            addCriterion("tp_mode >=", value, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeLessThan(Short value) {
            addCriterion("tp_mode <", value, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeLessThanOrEqualTo(Short value) {
            addCriterion("tp_mode <=", value, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeIn(List<Short> values) {
            addCriterion("tp_mode in", values, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeNotIn(List<Short> values) {
            addCriterion("tp_mode not in", values, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeBetween(Short value1, Short value2) {
            addCriterion("tp_mode between", value1, value2, "tpMode");
            return (Criteria) this;
        }

        public Criteria andTpModeNotBetween(Short value1, Short value2) {
            addCriterion("tp_mode not between", value1, value2, "tpMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeIsNull() {
            addCriterion("code_mode is null");
            return (Criteria) this;
        }

        public Criteria andCodeModeIsNotNull() {
            addCriterion("code_mode is not null");
            return (Criteria) this;
        }

        public Criteria andCodeModeEqualTo(Short value) {
            addCriterion("code_mode =", value, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeNotEqualTo(Short value) {
            addCriterion("code_mode <>", value, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeGreaterThan(Short value) {
            addCriterion("code_mode >", value, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeGreaterThanOrEqualTo(Short value) {
            addCriterion("code_mode >=", value, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeLessThan(Short value) {
            addCriterion("code_mode <", value, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeLessThanOrEqualTo(Short value) {
            addCriterion("code_mode <=", value, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeIn(List<Short> values) {
            addCriterion("code_mode in", values, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeNotIn(List<Short> values) {
            addCriterion("code_mode not in", values, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeBetween(Short value1, Short value2) {
            addCriterion("code_mode between", value1, value2, "codeMode");
            return (Criteria) this;
        }

        public Criteria andCodeModeNotBetween(Short value1, Short value2) {
            addCriterion("code_mode not between", value1, value2, "codeMode");
            return (Criteria) this;
        }

        public Criteria andTpPathIsNull() {
            addCriterion("tp_path is null");
            return (Criteria) this;
        }

        public Criteria andTpPathIsNotNull() {
            addCriterion("tp_path is not null");
            return (Criteria) this;
        }

        public Criteria andTpPathEqualTo(String value) {
            addCriterion("tp_path =", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathNotEqualTo(String value) {
            addCriterion("tp_path <>", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathGreaterThan(String value) {
            addCriterion("tp_path >", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathGreaterThanOrEqualTo(String value) {
            addCriterion("tp_path >=", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathLessThan(String value) {
            addCriterion("tp_path <", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathLessThanOrEqualTo(String value) {
            addCriterion("tp_path <=", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathLike(String value) {
            addCriterion("tp_path like", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathNotLike(String value) {
            addCriterion("tp_path not like", value, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathIn(List<String> values) {
            addCriterion("tp_path in", values, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathNotIn(List<String> values) {
            addCriterion("tp_path not in", values, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathBetween(String value1, String value2) {
            addCriterion("tp_path between", value1, value2, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpPathNotBetween(String value1, String value2) {
            addCriterion("tp_path not between", value1, value2, "tpPath");
            return (Criteria) this;
        }

        public Criteria andTpShowIsNull() {
            addCriterion("tp_show is null");
            return (Criteria) this;
        }

        public Criteria andTpShowIsNotNull() {
            addCriterion("tp_show is not null");
            return (Criteria) this;
        }

        public Criteria andTpShowEqualTo(Short value) {
            addCriterion("tp_show =", value, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowNotEqualTo(Short value) {
            addCriterion("tp_show <>", value, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowGreaterThan(Short value) {
            addCriterion("tp_show >", value, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowGreaterThanOrEqualTo(Short value) {
            addCriterion("tp_show >=", value, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowLessThan(Short value) {
            addCriterion("tp_show <", value, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowLessThanOrEqualTo(Short value) {
            addCriterion("tp_show <=", value, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowIn(List<Short> values) {
            addCriterion("tp_show in", values, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowNotIn(List<Short> values) {
            addCriterion("tp_show not in", values, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowBetween(Short value1, Short value2) {
            addCriterion("tp_show between", value1, value2, "tpShow");
            return (Criteria) this;
        }

        public Criteria andTpShowNotBetween(Short value1, Short value2) {
            addCriterion("tp_show not between", value1, value2, "tpShow");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNull() {
            addCriterion("is_top is null");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNotNull() {
            addCriterion("is_top is not null");
            return (Criteria) this;
        }

        public Criteria andIsTopEqualTo(Byte value) {
            addCriterion("is_top =", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotEqualTo(Byte value) {
            addCriterion("is_top <>", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThan(Byte value) {
            addCriterion("is_top >", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_top >=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThan(Byte value) {
            addCriterion("is_top <", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThanOrEqualTo(Byte value) {
            addCriterion("is_top <=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopIn(List<Byte> values) {
            addCriterion("is_top in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotIn(List<Byte> values) {
            addCriterion("is_top not in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopBetween(Byte value1, Byte value2) {
            addCriterion("is_top between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotBetween(Byte value1, Byte value2) {
            addCriterion("is_top not between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andTopModeIsNull() {
            addCriterion("top_mode is null");
            return (Criteria) this;
        }

        public Criteria andTopModeIsNotNull() {
            addCriterion("top_mode is not null");
            return (Criteria) this;
        }

        public Criteria andTopModeEqualTo(Short value) {
            addCriterion("top_mode =", value, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeNotEqualTo(Short value) {
            addCriterion("top_mode <>", value, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeGreaterThan(Short value) {
            addCriterion("top_mode >", value, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeGreaterThanOrEqualTo(Short value) {
            addCriterion("top_mode >=", value, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeLessThan(Short value) {
            addCriterion("top_mode <", value, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeLessThanOrEqualTo(Short value) {
            addCriterion("top_mode <=", value, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeIn(List<Short> values) {
            addCriterion("top_mode in", values, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeNotIn(List<Short> values) {
            addCriterion("top_mode not in", values, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeBetween(Short value1, Short value2) {
            addCriterion("top_mode between", value1, value2, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopModeNotBetween(Short value1, Short value2) {
            addCriterion("top_mode not between", value1, value2, "topMode");
            return (Criteria) this;
        }

        public Criteria andTopNumIsNull() {
            addCriterion("top_num is null");
            return (Criteria) this;
        }

        public Criteria andTopNumIsNotNull() {
            addCriterion("top_num is not null");
            return (Criteria) this;
        }

        public Criteria andTopNumEqualTo(Integer value) {
            addCriterion("top_num =", value, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumNotEqualTo(Integer value) {
            addCriterion("top_num <>", value, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumGreaterThan(Integer value) {
            addCriterion("top_num >", value, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("top_num >=", value, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumLessThan(Integer value) {
            addCriterion("top_num <", value, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumLessThanOrEqualTo(Integer value) {
            addCriterion("top_num <=", value, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumIn(List<Integer> values) {
            addCriterion("top_num in", values, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumNotIn(List<Integer> values) {
            addCriterion("top_num not in", values, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumBetween(Integer value1, Integer value2) {
            addCriterion("top_num between", value1, value2, "topNum");
            return (Criteria) this;
        }

        public Criteria andTopNumNotBetween(Integer value1, Integer value2) {
            addCriterion("top_num not between", value1, value2, "topNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("order_num is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("order_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumEqualTo(Integer value) {
            addCriterion("order_num =", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotEqualTo(Integer value) {
            addCriterion("order_num <>", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThan(Integer value) {
            addCriterion("order_num >", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_num >=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThan(Integer value) {
            addCriterion("order_num <", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(Integer value) {
            addCriterion("order_num <=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumIn(List<Integer> values) {
            addCriterion("order_num in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotIn(List<Integer> values) {
            addCriterion("order_num not in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumBetween(Integer value1, Integer value2) {
            addCriterion("order_num between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotBetween(Integer value1, Integer value2) {
            addCriterion("order_num not between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeptsIsNull() {
            addCriterion("depts is null");
            return (Criteria) this;
        }

        public Criteria andDeptsIsNotNull() {
            addCriterion("depts is not null");
            return (Criteria) this;
        }

        public Criteria andDeptsEqualTo(String value) {
            addCriterion("depts =", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsNotEqualTo(String value) {
            addCriterion("depts <>", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsGreaterThan(String value) {
            addCriterion("depts >", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsGreaterThanOrEqualTo(String value) {
            addCriterion("depts >=", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsLessThan(String value) {
            addCriterion("depts <", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsLessThanOrEqualTo(String value) {
            addCriterion("depts <=", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsLike(String value) {
            addCriterion("depts like", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsNotLike(String value) {
            addCriterion("depts not like", value, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsIn(List<String> values) {
            addCriterion("depts in", values, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsNotIn(List<String> values) {
            addCriterion("depts not in", values, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsBetween(String value1, String value2) {
            addCriterion("depts between", value1, value2, "depts");
            return (Criteria) this;
        }

        public Criteria andDeptsNotBetween(String value1, String value2) {
            addCriterion("depts not between", value1, value2, "depts");
            return (Criteria) this;
        }

        public Criteria andIsSignIsNull() {
            addCriterion("is_sign is null");
            return (Criteria) this;
        }

        public Criteria andIsSignIsNotNull() {
            addCriterion("is_sign is not null");
            return (Criteria) this;
        }

        public Criteria andIsSignEqualTo(Boolean value) {
            addCriterion("is_sign =", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignNotEqualTo(Boolean value) {
            addCriterion("is_sign <>", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignGreaterThan(Boolean value) {
            addCriterion("is_sign >", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_sign >=", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignLessThan(Boolean value) {
            addCriterion("is_sign <", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignLessThanOrEqualTo(Boolean value) {
            addCriterion("is_sign <=", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignIn(List<Boolean> values) {
            addCriterion("is_sign in", values, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignNotIn(List<Boolean> values) {
            addCriterion("is_sign not in", values, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sign between", value1, value2, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sign not between", value1, value2, "isSign");
            return (Criteria) this;
        }

        public Criteria andSignIdsIsNull() {
            addCriterion("sign_ids is null");
            return (Criteria) this;
        }

        public Criteria andSignIdsIsNotNull() {
            addCriterion("sign_ids is not null");
            return (Criteria) this;
        }

        public Criteria andSignIdsEqualTo(String value) {
            addCriterion("sign_ids =", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsNotEqualTo(String value) {
            addCriterion("sign_ids <>", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsGreaterThan(String value) {
            addCriterion("sign_ids >", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsGreaterThanOrEqualTo(String value) {
            addCriterion("sign_ids >=", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsLessThan(String value) {
            addCriterion("sign_ids <", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsLessThanOrEqualTo(String value) {
            addCriterion("sign_ids <=", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsLike(String value) {
            addCriterion("sign_ids like", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsNotLike(String value) {
            addCriterion("sign_ids not like", value, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsIn(List<String> values) {
            addCriterion("sign_ids in", values, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsNotIn(List<String> values) {
            addCriterion("sign_ids not in", values, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsBetween(String value1, String value2) {
            addCriterion("sign_ids between", value1, value2, "signIds");
            return (Criteria) this;
        }

        public Criteria andSignIdsNotBetween(String value1, String value2) {
            addCriterion("sign_ids not between", value1, value2, "signIds");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gx_content_type
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 26 16:50:52 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gx_content_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}