package com.yanghua.gongxiang.bean;

public class Depts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.com_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.code
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.shortname
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.shortword
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String shortword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.is_publish
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte isPublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.is_sync
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte isSync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_depts.parent_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.id
     *
     * @return the value of gx_depts.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.id
     *
     * @param id the value for gx_depts.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.com_id
     *
     * @return the value of gx_depts.com_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.com_id
     *
     * @param comId the value for gx_depts.com_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.name
     *
     * @return the value of gx_depts.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.name
     *
     * @param name the value for gx_depts.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.code
     *
     * @return the value of gx_depts.code
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.code
     *
     * @param code the value for gx_depts.code
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.shortname
     *
     * @return the value of gx_depts.shortname
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.shortname
     *
     * @param shortname the value for gx_depts.shortname
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.shortword
     *
     * @return the value of gx_depts.shortword
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getShortword() {
        return shortword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.shortword
     *
     * @param shortword the value for gx_depts.shortword
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setShortword(String shortword) {
        this.shortword = shortword == null ? null : shortword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.type
     *
     * @return the value of gx_depts.type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.type
     *
     * @param type the value for gx_depts.type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.order_num
     *
     * @return the value of gx_depts.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.order_num
     *
     * @param orderNum the value for gx_depts.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.is_publish
     *
     * @return the value of gx_depts.is_publish
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getIsPublish() {
        return isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.is_publish
     *
     * @param isPublish the value for gx_depts.is_publish
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIsPublish(Byte isPublish) {
        this.isPublish = isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.is_sync
     *
     * @return the value of gx_depts.is_sync
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.is_sync
     *
     * @param isSync the value for gx_depts.is_sync
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIsSync(Byte isSync) {
        this.isSync = isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.status
     *
     * @return the value of gx_depts.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.status
     *
     * @param status the value for gx_depts.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_depts.parent_id
     *
     * @return the value of gx_depts.parent_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_depts.parent_id
     *
     * @param parentId the value for gx_depts.parent_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}