package com.yanghua.gongxiang.bean;

import java.util.Date;

public class GradeLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_level.id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_level.name
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_level.max_score
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Integer maxScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_level.created_id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Integer createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_level.created_time
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_level.status
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_level.id
     *
     * @return the value of gx_grade_level.id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_level.id
     *
     * @param id the value for gx_grade_level.id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_level.name
     *
     * @return the value of gx_grade_level.name
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_level.name
     *
     * @param name the value for gx_grade_level.name
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_level.max_score
     *
     * @return the value of gx_grade_level.max_score
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_level.max_score
     *
     * @param maxScore the value for gx_grade_level.max_score
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_level.created_id
     *
     * @return the value of gx_grade_level.created_id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Integer getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_level.created_id
     *
     * @param createdId the value for gx_grade_level.created_id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setCreatedId(Integer createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_level.created_time
     *
     * @return the value of gx_grade_level.created_time
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_level.created_time
     *
     * @param createdTime the value for gx_grade_level.created_time
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_level.status
     *
     * @return the value of gx_grade_level.status
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_level.status
     *
     * @param status the value for gx_grade_level.status
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}