package com.yanghua.gongxiang.bean;

import java.util.Date;

public class GradeHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_history.id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_history.mem_id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Integer memId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_history.score
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private Short score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_history.created_time
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private String createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_grade_history.note
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_history.id
     *
     * @return the value of gx_grade_history.id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_history.id
     *
     * @param id the value for gx_grade_history.id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_history.mem_id
     *
     * @return the value of gx_grade_history.mem_id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Integer getMemId() {
        return memId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_history.mem_id
     *
     * @param memId the value for gx_grade_history.mem_id
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setMemId(Integer memId) {
        this.memId = memId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_history.score
     *
     * @return the value of gx_grade_history.score
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public Short getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_history.score
     *
     * @param score the value for gx_grade_history.score
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setScore(Short score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_history.created_time
     *
     * @return the value of gx_grade_history.created_time
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_history.created_time
     *
     * @param createdTime the value for gx_grade_history.created_time
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_grade_history.note
     *
     * @return the value of gx_grade_history.note
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public String getNote() {
        return note;
    }

    @Override
    public String toString() {
        return "GradeHistory{" +
                "id=" + id +
                ", memId=" + memId +
                ", score=" + score +
                ", createdTime=" + createdTime +
                ", note='" + note + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_grade_history.note
     *
     * @param note the value for gx_grade_history.note
     *
     * @mbg.generated Wed Jan 31 20:33:27 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}