package com.yanghua.gongxiang.bean;

public class Roles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.pid
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.role_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.remark
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_roles.funcs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String funcs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.id
     *
     * @return the value of gx_roles.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.id
     *
     * @param id the value for gx_roles.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.pid
     *
     * @return the value of gx_roles.pid
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.pid
     *
     * @param pid the value for gx_roles.pid
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.name
     *
     * @return the value of gx_roles.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.name
     *
     * @param name the value for gx_roles.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.role_type
     *
     * @return the value of gx_roles.role_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.role_type
     *
     * @param roleType the value for gx_roles.role_type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.remark
     *
     * @return the value of gx_roles.remark
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.remark
     *
     * @param remark the value for gx_roles.remark
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.order_num
     *
     * @return the value of gx_roles.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.order_num
     *
     * @param orderNum the value for gx_roles.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.status
     *
     * @return the value of gx_roles.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.status
     *
     * @param status the value for gx_roles.status
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_roles.funcs
     *
     * @return the value of gx_roles.funcs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getFuncs() {
        return funcs;
    }

    @Override
    public String toString() {
        return "Roles{" +
                "id=" + id +
                ", pid=" + pid +
                ", name='" + name + '\'' +
                ", roleType='" + roleType + '\'' +
                ", remark='" + remark + '\'' +
                ", orderNum=" + orderNum +
                ", status=" + status +
                ", funcs='" + funcs + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_roles.funcs
     *
     * @param funcs the value for gx_roles.funcs
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setFuncs(String funcs) {
        this.funcs = funcs == null ? null : funcs.trim();
    }
}