package com.yanghua.gongxiang.bean;

public class SysConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.category
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.title
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.icon
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.cur_value
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String curValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.is_custom
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Byte isCustom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_config.value
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.id
     *
     * @return the value of gx_sys_config.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.id
     *
     * @param id the value for gx_sys_config.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.category
     *
     * @return the value of gx_sys_config.category
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.category
     *
     * @param category the value for gx_sys_config.category
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.name
     *
     * @return the value of gx_sys_config.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.name
     *
     * @param name the value for gx_sys_config.name
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.title
     *
     * @return the value of gx_sys_config.title
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.title
     *
     * @param title the value for gx_sys_config.title
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.icon
     *
     * @return the value of gx_sys_config.icon
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.icon
     *
     * @param icon the value for gx_sys_config.icon
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.cur_value
     *
     * @return the value of gx_sys_config.cur_value
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getCurValue() {
        return curValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.cur_value
     *
     * @param curValue the value for gx_sys_config.cur_value
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setCurValue(String curValue) {
        this.curValue = curValue == null ? null : curValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.type
     *
     * @return the value of gx_sys_config.type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.type
     *
     * @param type the value for gx_sys_config.type
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.is_custom
     *
     * @return the value of gx_sys_config.is_custom
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Byte getIsCustom() {
        return isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.is_custom
     *
     * @param isCustom the value for gx_sys_config.is_custom
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIsCustom(Byte isCustom) {
        this.isCustom = isCustom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.order_num
     *
     * @return the value of gx_sys_config.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.order_num
     *
     * @param orderNum the value for gx_sys_config.order_num
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_config.value
     *
     * @return the value of gx_sys_config.value
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_config.value
     *
     * @param value the value for gx_sys_config.value
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}