package com.yanghua.gongxiang.bean;

import java.util.Date;

public class SysLogs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.dept_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.user_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.created_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.ip_addr
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String ipAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.browser
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.client_os
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String clientOs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gx_sys_logs.user_agent
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    private String userAgent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.id
     *
     * @return the value of gx_sys_logs.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.id
     *
     * @param id the value for gx_sys_logs.id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.dept_id
     *
     * @return the value of gx_sys_logs.dept_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.dept_id
     *
     * @param deptId the value for gx_sys_logs.dept_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.user_id
     *
     * @return the value of gx_sys_logs.user_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.user_id
     *
     * @param userId the value for gx_sys_logs.user_id
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.created_time
     *
     * @return the value of gx_sys_logs.created_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.created_time
     *
     * @param createdTime the value for gx_sys_logs.created_time
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.ip_addr
     *
     * @return the value of gx_sys_logs.ip_addr
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.ip_addr
     *
     * @param ipAddr the value for gx_sys_logs.ip_addr
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.browser
     *
     * @return the value of gx_sys_logs.browser
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.browser
     *
     * @param browser the value for gx_sys_logs.browser
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.client_os
     *
     * @return the value of gx_sys_logs.client_os
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getClientOs() {
        return clientOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.client_os
     *
     * @param clientOs the value for gx_sys_logs.client_os
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setClientOs(String clientOs) {
        this.clientOs = clientOs == null ? null : clientOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gx_sys_logs.user_agent
     *
     * @return the value of gx_sys_logs.user_agent
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gx_sys_logs.user_agent
     *
     * @param userAgent the value for gx_sys_logs.user_agent
     *
     * @mbg.generated Fri Jan 26 16:50:52 CST 2018
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }
}